services:
  backend:
    depends_on:
      - mysql
    container_name: nest_backend
    build: ./backend
    image: node:latest
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    networks:
      - appNet
    restart: always
    stdin_open: true
    tty: true