services:
  mysql:
    # depends_on:
    #   - ...
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - ./.env
    # networks:
    #   - ...
    restart: always