services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    networks:
      - appNet
    restart: always

  backend:
    depends_on:
      - mysql
    container_name: nest_backend
    build: ./backend
    image: node:latest
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    networks:
      - appNet
    restart: always

  frontend:
    depends_on:
      - mysql
      - backend
    container_name: react_frontend
    build: ./frontend
    image: node:latest
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    networks:
      - appNet
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - appNet
    restart: always

networks:
  appNet:
